import { Card } from "./types";

export const footballCards: Card[] = [
  { id: 1, set: '2022 Panini Mosaic', number: '71', player: 'AJ Dillon',
    parallels: [
      { id: 1, name: 'Base', owned: true, purchasePrice: 0.99, purchaseDate: new Date('2025-02-23') },
      { id: 2, name: 'Honeycomb', owned: true, purchasePrice: 91, purchaseDate: new Date('2025-03-17') },
      { id: 3, name: 'Mosaic', owned: true, purchasePrice: 4.79, purchaseDate: new Date('2025-02-24') },
      { id: 4, name: 'Camo Pink Mosaic', owned: true, purchasePrice: 1, purchaseDate: new Date('2025-02-23') },
      { id: 5, name: 'Choice Peacock Mosaic', owned: false },
      { id: 6, name: 'Genesis Mosaic', owned: true, purchasePrice: 43, purchaseDate: new Date('2025-02-28') },
      { id: 7, name: 'Green Mosaic', owned: true, purchasePrice: 1.69, purchaseDate: new Date('2025-02-23') },
      { id: 8, name: 'No Huddle Silver Mosaic', owned: true, purchasePrice: 2.99, purchaseDate: new Date('2025-02-23') },
      { id: 9, name: 'Reactive Orange Mosaic', owned: true, purchasePrice: 1.99, purchaseDate: new Date('2025-02-23') },
      { id: 10, name: 'Red Mosaic', owned: true, purchasePrice: 5.99, purchaseDate: new Date('2025-02-28') },
      { id: 11, name: 'Silver', owned: true, purchasePrice: 1.99, purchaseDate: new Date('2025-02-23') },
      { id: 12, name: 'White Sparkle', owned: true, purchasePrice: 58.04, purchaseDate: new Date('2025-02-28') },
      { id: 13, name: 'Red Sparkle', owned: true, purchasePrice: 3, purchaseDate: new Date('2025-02-28') },
      { id: 14, name: 'Blue Sparkle', owned: true, purchasePrice: 12.99, purchaseDate: new Date('2025-02-28') },
      { id: 15, name: 'Gold Sparkle', owned: true, purchasePrice: 39.85, purchaseDate: new Date('2025-03-20') },
      { id: 16, name: 'Blue Mosaic', numbered: 99, owned: true, purchasePrice: 12.59, purchaseDate: new Date('2023-04-22') },
      { id: 17, name: 'Choice Fusion Red and Yellow Mosaic', numbered: 80, owned: true, purchasePrice: 5.40, purchaseDate: new Date('2025-02-23') },
      { id: 18, name: 'No Huddle Blue Mosaic', numbered: 75, owned: true, purchasePrice: 8.09, purchaseDate: new Date('2025-02-23') },
      { id: 19, name: 'No Huddle Purple Mosaic', numbered: 50, owned: true, purchasePrice: 10, purchaseDate: new Date('2025-02-27') },
      { id: 20, name: 'Purple Mosaic', numbered: 49, owned: true, purchasePrice: 6.74, purchaseDate: new Date('2025-02-23') },
      { id: 21, name: 'Orange Fluorescent Mosaic', numbered: 25, owned: true, purchasePrice: 29.29, purchaseDate: new Date('2025-02-27') },
      { id: 22, name: 'White Mosaic', numbered: 25, owned: true, purchasePrice: 60, purchaseDate: new Date('2025-02-27') },
      { id: 23, name: 'No Huddle Pink Mosaic', numbered: 20, owned: false },
      { id: 24, name: 'Gold Wave Mosaic', numbered: 17, owned: true, purchasePrice: 25, purchaseDate: new Date('2025-02-23') },
      { id: 25, name: 'Blue Fluorescent Mosaic', numbered: 15, owned: true, purchasePrice: 27.99, purchaseDate: new Date('2025-02-26') },
      { id: 26, name: 'Green Sparkle', numbered: 15, owned: false },
      { id: 27, name: 'Tessellation Mosaic', numbered: 15, owned: true, purchasePrice: 68, purchaseDate: new Date('2025-02-26') },
      { id: 28, name: 'Green Swirl Mosaic', numbered: 11, owned: false },
      { id: 29, name: 'Pink Swirl Mosaic', numbered: 11, owned: false },
      { id: 30, name: 'Gold Mosaic', numbered: 10, owned: true, purchasePrice: 70, purchaseDate: new Date('2025-02-27') },
      { id: 31, name: 'No Huddle Gold Mosaic', numbered: 10, owned: false },
      { id: 32, name: 'Red Wave Mosaic', numbered: 9, owned: false },
      { id: 33, name: 'Choice Black Gold Mosaic', numbered: 8, owned: false },
      { id: 34, name: 'Black Mosaic', numbered: 1, owned: false },
      { id: 35, name: 'Choice Nebula Mosaic', numbered: 1, owned: false },
      { id: 36, name: 'No Huddle Black Mosaic', numbered: 1, owned: false },
    ]
  }
];